<?php $_reviews = $this->getReviewsData();?>


<div class="block block-productactivity">
    <div class="block-content">
        <div class="content-home-wrapper">
            <?php $i=0; $total = count($_reviews); foreach($_reviews as $review): ?>
                <?php 
                    

                    $ratings = $review['ratings'][0];
                    $_product = $review['product'];
                    
                    $i++;
                    $class ='';
                    if ($i == 1) $class ='class="first"';
                    if ($i == $total ) $class ='class="last"';
                ?>
                <dl <?php echo $class; ?>>
                    <div class="product-image">
                        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(132, 124); ?>" width="132" height="124" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
                    </div>                    
                    <dt>
                        <a href="<?php echo $review['review_url']; ?>"><?php echo $review['title']; ?></a> <?php echo $this->__('Review by');?> <strong><?php echo $review['nickname']; ?></strong>
                    </dt>
                    <dd>
                        <table class="ratings-table">
                                <col width="1">
                                <col>
                                <tbody>
                                    <?php foreach($ratings as $k => $rating): ?>         
                                        <tr>
                                            <th><?php echo $k;?></th>
                                            <td>
                                                <div class="rating-box">
                                                    <div style="width: <?php echo $rating; ?>%;" class="rating"></div>
                                                </div>
                                            </td>
                                        </tr>
                                    <?php endforeach; ?>                                    
                                </tbody>
                            </table>
                        <?php echo $review['detail']; ?><br/>


                        <?php if (Mage::getStoreConfig('productactivity/options/actions')):?>
                            <a class="link-cart" href="<?php echo $this->getAddToCartUrl($_product) ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>"><?php echo $this->__('Add to Cart') ?></a>


                            <div class="additional-links">    
                                <?php $_wishlistSubmitUrl = $this->helper('wishlist')->getAddUrl($_product); ?>
                                <ul class="add-to-links">
                                <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                    <li><a href="<?php echo $_wishlistSubmitUrl ?>" onclick="productAddToCartForm.submitLight(this, '<?php echo $_wishlistSubmitUrl ?>'); return false;" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
                                <?php endif; ?>
                                <?php
                                    $_compareUrl = $this->helper('catalog/product_compare')->getAddUrl($_product);
                                ?>
                                <?php if($_compareUrl) : ?>
                                    <li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
                                <?php endif; ?>
                                </ul>   
                            </div>                                            
                        <?php endif; ?>         
                            
                    </dd>
                </dl>
            <?php endforeach; ?>
            <?php if ($i==0): ?>
                <ol id="productactivity-no-products" class="mini-products-list">
                    <li class="item odd">
                        <?php echo Mage::getStoreConfig('productactivity/options/noproduct'); ?>
                    </li>
                </ol>
            <?php endif;?>
        </div>
    </div>
</div>
