<?php $_products = $this->getTopRatedProduct();?>
<?php $_collectionSize = count($_products); ?>
<?php $_columnCount = Mage::getStoreConfig('productactivity/options/count'); ?>


<div class="block block-productactivity">
    <div class="block-content">

            <?php $i=0; foreach($_products as $_rating): ?>
            <?php $_product = $_rating['product']; ?>

                <?php if ($i++%$_columnCount==0): ?>
                <ul class="products-grid">
                <?php endif ?>

                        <?php if ($_product->getData('is_salable')): ?>
                            <li class="item<?php if($i==sizeof($_products) ): ?> last<?php endif; ?>">
                                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'thumbnail')->resize(130); ?>" width="130" height="130" alt="" /></a>
                                <div class="product-details">
                                    <p class="product-name"><a href="<?php echo $this->getProductUrl($_product) ?>"><?php echo $this->htmlEscape($_product->getName()) ?></a></p>
                                    <?php if (Mage::getStoreConfig('productactivity/options/price')):?>
                                        <?php echo $this->getPriceHtml($_product, true) ?>
                                    <?php endif; ?>
                                    <?php if (Mage::getStoreConfig('productactivity/options/actions')):?>
                                        <a class="link-cart" href="<?php echo $this->getAddToCartUrl($_product) ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>"><?php echo $this->__('Add to Cart') ?></a>


                                        <div class="additional-links">    
                                            <?php $_wishlistSubmitUrl = $this->helper('wishlist')->getAddUrl($_product); ?>
                                            <ul class="add-to-links">
                                            <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                                <li><a href="<?php echo $_wishlistSubmitUrl ?>" onclick="productAddToCartForm.submitLight(this, '<?php echo $_wishlistSubmitUrl ?>'); return false;" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
                                            <?php endif; ?>
                                            <?php
                                                $_compareUrl = $this->helper('catalog/product_compare')->getAddUrl($_product);
                                            ?>
                                            <?php if($_compareUrl) : ?>
                                                <li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
                                            <?php endif; ?>
                                            </ul>   
                                        </div>                                            
                                    <?php endif; ?>
                                </div>
                            </li>
                        <?php else: ?>
                            <?php if( Mage::getStoreConfig('productactivity/options/salable')) : ?>
                                <li class="item">
                                    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'thumbnail')->resize(130); ?>" width="130" height="130" alt="" /></a>
                                    <div class="product-details">
                                        <p class="product-name"><a href="<?php echo $this->getProductUrl($_product) ?>"><?php echo $this->htmlEscape($_product->getName()) ?></a></p>
                                        <?php if (Mage::getStoreConfig('productactivity/options/price')):?>
                                            <?php echo $this->getPriceHtml($_product, true) ?>
                                        <?php endif; ?>
                                        <?php if (Mage::getStoreConfig('productactivity/options/actions')):?>
                                            <a class="link-cart" href="<?php echo $this->getAddToCartUrl($_product) ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>"><?php echo $this->__('Add to Cart') ?></a>
                                        
                                                
                                            <div class="additional-links">    
                                                <?php $_wishlistSubmitUrl = $this->helper('wishlist')->getAddUrl($_product); ?>
                                                <ul class="add-to-links">
                                                <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                                    <li><a href="<?php echo $_wishlistSubmitUrl ?>" onclick="productAddToCartForm.submitLight(this, '<?php echo $_wishlistSubmitUrl ?>'); return false;" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
                                                <?php endif; ?>
                                                <?php
                                                    $_compareUrl = $this->helper('catalog/product_compare')->getAddUrl($_product);
                                                ?>
                                                <?php if($_compareUrl) : ?>
                                                    <li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
                                                <?php endif; ?>
                                                </ul>   
                                            </div>                                                
                                        <?php endif; ?>
                                    </div>
                                </li>
                            <?php endif; ?>
                        <?php endif; ?>

                <?php if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
                </ul>
                <?php endif ?>


            <?php endforeach; ?>

    </div>
</div>